server:
   port: 8082
   servlet:
      contextPath: /cdmsapi
spring:
   datasource:
      driver: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      continueOnError: true
      initialize: false
      initialSize: 0
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 5000
      minIdle: 0
   jpa:
      database: ORACLE
      properties:
         hibernate:
            boot:
               allow_jdbc_metadata_access: false
      hibernate:
         ddl-auto: none
      show-sql: true
   application:
      name: cdmsapi
